=== venkateshpavuluri/Unmarshaling/src/main/webapp/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mnt.com/bean/student" xmlns:tns="http://mnt.com/bean/student" elementFormDefault="qualified">
<xs:element name="student" type="tns:students">

</xs:element>
<xs:complexType name="students">
<xs:sequence>
<xs:element name="name" type="xs:string"></xs:element>
<xs:element name="password" type="xs:string"></xs:element>
<xs:element name="userId" type="xs:string"></xs:element>
<xs:element name="passId" type="xs:string"></xs:element>
<xs:element name="employees" type="tns:employees">
</xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="employees">
<xs:sequence>
<xs:element name="empName" type="xs:string"></xs:element>
<xs:element name="empId" type="xs:integer"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:schema>

=== venkateshpavuluri/Unmarshaling/src/main/webapp/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:student xmlns:tns="http://mnt.com/bean/students" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mnt.com/bean/students student.xsd ">
  <tns:name>Nani</tns:name>
  <tns:password>123456</tns:password>
  <tns:userId>123</tns:userId>
  <tns:passId>123</tns:passId>
  <tns:employees>
    <tns:empName>some</tns:empName>
    <tns:empId>123</tns:empId>
  </tns:employees>
</tns:student>
